name: Build & Test

on: workflow_call
jobs:
  build-test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '17'
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    - run: npm run test