name: Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs: 
  lint: 
    uses: saunah/saunah-frontend/.github/workflows/lint.yml

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '17'
        cache: 'npm'
    - run: npm ci
    - run: npm run build

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '17'
        cache: 'npm'
    - run: npm ci
    - run: npm run test

    container:

    name: Create and Publish Container
    runs-on: ubuntu-latest
    needs: [setup, build]
    if: ${{ github.ref == 'refs/heads/main' }}
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create Container
        uses: gradle/gradle-build-action@v2.1.4
        with:
          arguments: bootBuildImage --imageName ghcr.io/saunah/saunah-backend:${{ needs.setup.outputs.containerTag }}

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to Registry
        run: docker push ghcr.io/saunah/saunah-backend:${{ needs.setup.outputs.containerTag }}

  