name: Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build & test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build with Node v17
      uses: actions/setup-node@v2
      with:
        node-version: '17'
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run test
