name: Build & Test

on: workflow_call
jobs:
  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '17'
        cache: 'npm'
    - run: npm ci
    - run: npm run build

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '17'
        cache: 'npm'
    - run: npm ci
    - run: npm run test
