name: Deploy

on: workflow_call
jobs:
  setup:
  runs-on: ubuntu-latest
  outputs:
    containerTag: ${{ steps.setConfigs.outputs.containerTag }}
  steps:
  - uses: actions/checkout@v2
  - name: Set Tag Output Variable
    id: setConfigs
    run: |
      if [ "${{ github.ref_type }}" == "tag" ]
      then
        echo "::set-output name=containerTag::${{ github.ref_name }}"
      else
        echo "::set-output name=containerTag::$(echo ${{ github.sha }} | cut -c 1-7)"
      fi
  
  container:
    needs: setup
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
    
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push docker container
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/saunah/saunah-frontend:${{ needs.setup.outputs.containerTag }}

    
  