name: Lint

on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Lint with Node v17
      uses: actions/setup-node@v2
      with:
        node-version: '17'
        cache: 'npm'
    - run: npm ci
    - run: npm run lint