name: On Main

on: 
  workflow_dispatch: push
    

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
  
  build:
    needs: lint
    uses: ./.github/workflows/build.yml

  deploy:
    needs: build
    uses: ./.github/workflows/deploy.yml