name: On Main

on: push
  # push:
  #   branches: main

jobs:
  lint:
    uses: ./.github/workflows/lint.yml
  
  build:
    needs: lint
    uses: ./.github/workflows/build.yml

  deploy:
    needs: build
    uses: ./.github/workflows/deploy.yml
