name: On Pull Request

on: 
  pull_request:
    branches: main

jobs:
  lint:
    uses: saunah/saunah-frontend/.github/workflows/lint.yml@main
  
  build:
    needs: lint
    uses: saunah/saunah-frontend/.github/workflows/build.yml@main