name: Pull Request Pipeline

on: 
  pull_request:
    branches: main

jobs:
  lint:
    uses: saunah/saunah-frontend/.github/workflows/lint.yml@main
  
  deploy:
    needs: lint
    uses: saunah/saunah-frontend/.github/workflows/deploy.yml@main


  