# This workflow tests the SauNah frontend application.

name: Test SauNah frontend

on:
  push:
    branches-ignore:
      - 'main'

jobs:
  build:
    name: Lint, Build, Test & Analyse
    uses: ./.github/workflows/build.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
