name: Setup values

on:
  workflow_call:
    outputs:
      containerTag:
        value: ${{ jobs.setup.outputs.containerTag }}
      k8sContext:
        value: ${{ jobs.setup.outputs.k8sContext }}
      k8sConfigValues:
        value: ${{ jobs.setup.outputs.k8sConfigValues }}

jobs:
  setup:
    name: Setup Configuration Values
    runs-on: ubuntu-latest
    outputs:
      containerTag: ${{ steps.setConfigs.outputs.containerTag }}
      k8sContext: ${{ steps.setConfigs.outputs.k8sContext }}
      k8sConfigValues: ${{ steps.setConfigs.outputs.k8sConfigValues }}
      deploymentEnv: ${{ steps.setConfigs.outputs.deploymentEnv }}
    steps:
      - uses: actions/checkout@v2
      - name: Set Tag Ouput Variable
        id: setConfigs
        run: |
          if [ "${{ github.ref_type }}" == "tag" ]
          then
            echo "::set-output name=containerTag::${{ github.ref_name }}"
            echo "::set-output name=k8sContext::init-lab-prod"
            echo "::set-output name=k8sConfigValues::values-prod.yaml"
          else
            echo "::set-output name=containerTag::$(echo ${{ github.sha }} | cut -c 1-7)"
            echo "::set-output name=k8sContext::init-lab-staging"
            echo "::set-output name=k8sConfigValues::values-staging.yaml"
          fi
